[project]
name = "lipvm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
testpaths = "tests"
dependencies = [
    "jsonrpclib>=0.2.1",
    "pyecore>=0.15.2",
    "pyecoregen>=0.5.1",
    "textx>=4.3.0",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.19",
    "pytest>=9.0.2",
    "pyvis>=0.3.2",
]

[tool.pytest.ini_options]
pythonpath = ["."]

