"""
Automatically generated by Claude Sonnet 4.6.

Export pyecore-based language definitions to a single .ecore file.

A language definition is typically split across several Python modules
(e.g. `languages.robot.runtime` and `languages.robot.syntax`), each
containing module-level `EClass`-based classes and `EEnum` instances.

This tool collects all classifiers defined in the given modules, plus any
classifier they reference (supertypes, attribute/reference types) from other
project modules such as `core.language`, so that the resulting `.ecore` file
is self-contained, and writes it as a single EPackage.
"""

import argparse
import importlib

from pyecore.ecore import EClass, EEnum, EPackage
from pyecore.resources import ResourceSet, URI


def _module_classifiers(module):
    """Returns the EClass/EEnum classifiers defined directly in `module`."""
    classifiers = []
    for value in vars(module).values():
        eclass = getattr(value, "eClass", None)
        if isinstance(eclass, EClass) and getattr(value, "__module__", None) == module.__name__:
            classifiers.append(eclass)
        elif isinstance(value, EEnum) and value.ePackage is None:
            classifiers.append(value)
    return classifiers


def _referenced_classifiers(classifier):
    """Returns the classifiers directly referenced by `classifier` (supertypes and feature types)."""
    if not isinstance(classifier, EClass):
        return []
    related = list(classifier.eSuperTypes)
    for feature in classifier.eStructuralFeatures:
        related.append(feature.eType)
    return related


def collect_classifiers(modules):
    """Collects all classifiers defined in `modules`, transitively including
    any other project-defined classifier they reference, so the result can
    be exported as a single, self-contained EPackage.

    Built-in Ecore classifiers (EInt, EString, ...) are excluded since they
    are part of the Ecore metamodel itself and do not need to be exported.
    """
    classifiers = []
    seen = set()

    def add(classifier):
        if classifier is None or id(classifier) in seen:
            return
        package = classifier.ePackage
        if package is not None and package.name == "ecore":
            return
        seen.add(id(classifier))
        classifiers.append(classifier)
        for related in _referenced_classifiers(classifier):
            add(related)

    for module in modules:
        for classifier in _module_classifiers(module):
            add(classifier)

    return classifiers


def export_to_ecore(modules, output_path, package_name, ns_uri=None, ns_prefix=None):
    """Exports the EClass/EEnum definitions found in `modules` to `output_path` as a single .ecore file."""
    package = EPackage(
        name=package_name,
        nsURI=ns_uri or f"http://{package_name}/",
        nsPrefix=ns_prefix or package_name,
    )

    for classifier in collect_classifiers(modules):
        if isinstance(classifier, EClass):
            # eOperations reflect the Python methods of the implementation classes.
            # They are not part of the language's abstract syntax / runtime structure
            # and some of them (e.g. name-mangled "__"-prefixed methods) cannot be
            # reloaded by pyecore, so they are dropped from the exported metamodel.
            classifier.eOperations.clear()
        package.eClassifiers.append(classifier)

    resource_set = ResourceSet()
    resource = resource_set.create_resource(URI(output_path))
    resource.append(package)
    resource.save()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "modules",
        nargs="+",
        help="Python modules to export, e.g. languages.robot.runtime languages.robot.syntax",
    )
    parser.add_argument("-o", "--output", required=True, help="Path to the .ecore file to write")
    parser.add_argument("-n", "--name", required=True, help="Name of the resulting EPackage")
    parser.add_argument("--ns-uri", help="nsURI of the resulting EPackage")
    parser.add_argument("--ns-prefix", help="nsPrefix of the resulting EPackage")
    args = parser.parse_args()

    modules = [importlib.import_module(name) for name in args.modules]
    export_to_ecore(modules, args.output, args.name, args.ns_uri, args.ns_prefix)


if __name__ == "__main__":
    main()
