"""
Automatically generated by Claude Sonnet 4.6.

Generate an interactive HTML diagram from a .ecore file.

Reads an Ecore metamodel and produces a force-directed graph where:
  - EClass nodes are shown as blue boxes
  - EEnum nodes are shown as green boxes
  - Inheritance (eSuperTypes) is shown as dashed gray arrows
  - References (EReference) are shown as solid arrows labelled with
    the reference name and multiplicity

Usage:
    uv run python tools/visualization.py path/to/model.ecore [-o output.html]
"""

import argparse
import os

from pyecore.ecore import EClass, EEnum
from pyecore.resources import ResourceSet, URI
from pyvis.network import Network


def load_package(ecore_path: str):
    rset = ResourceSet()
    resource = rset.get_resource(URI(ecore_path))
    return resource.contents[0]


def multiplicity(ref) -> str:
    lo = ref.lowerBound
    hi = ref.upperBound
    if hi == -1:
        hi = "*"
    if lo == hi:
        return str(lo)
    return f"{lo}..{hi}"


THEMES = {
    "dark": {
        "bgcolor": "#1a1a2e",
        "class_bg": "#4a90d9",   "class_border": "#2c5f8a",   "class_font": "white",
        "enum_bg":  "#4caf7d",   "enum_border":  "#2e7d52",   "enum_font":  "white",
        "inherit_color": "#888888",
        "contain_color": "#e07b39",
        "ref_color":     "#cccccc",
        "edge_font":     "#dddddd",
        "legend_bg":     "rgba(30,30,60,0.85)",
        "legend_border": "#555",
        "legend_color":  "#eee",
    },
    "light": {
        # Okabe-Ito palette — safe for deuteranopia, protanopia, and tritanopia
        "bgcolor": "#ffffff",
        "class_bg": "#d6eaf8",   "class_border": "#0072b2",   "class_font": "#000000",  # blue
        "enum_bg":  "#fef3cd",   "enum_border":  "#e69f00",   "enum_font":  "#000000",  # amber
        "inherit_color": "#0072b2",   # blue   — dashed
        "contain_color": "#d55e00",   # vermillion — solid thick
        "ref_color":     "#555555",   # dark gray  — solid thin
        "edge_font":     "#333333",
        "legend_bg":     "rgba(255,255,255,0.92)",
        "legend_border": "#bbbbbb",
        "legend_color":  "#111111",
    },
}

LEGEND_HTML = """
<div id="legend" style="
    position: fixed; bottom: 20px; left: 20px; z-index: 1000;
    background: {legend_bg}; border: 1px solid {legend_border};
    border-radius: 8px; padding: 12px 16px;
    font-family: monospace; font-size: 12px; color: {legend_color};
    line-height: 1.8;
">
  <b style="font-size:13px;">Legend</b><br>
  <span style="display:inline-block;width:14px;height:14px;background:{class_bg};border:2px solid {class_border};vertical-align:middle;margin-right:6px;"></span> EClass<br>
  <span style="display:inline-block;width:14px;height:14px;background:{enum_bg};border:2px solid {enum_border};vertical-align:middle;margin-right:6px;"></span> EEnum<br>
  <svg width="28" height="12" style="vertical-align:middle;margin-right:6px;">
    <line x1="0" y1="6" x2="22" y2="6" stroke="{inherit_color}" stroke-width="1.5" stroke-dasharray="4,2"/>
    <polygon points="22,3 28,6 22,9" fill="{inherit_color}"/>
  </svg> Inheritance<br>
  <svg width="28" height="12" style="vertical-align:middle;margin-right:6px;">
    <line x1="0" y1="6" x2="22" y2="6" stroke="{contain_color}" stroke-width="2"/>
    <polygon points="22,3 28,6 22,9" fill="{contain_color}"/>
  </svg> Containment reference<br>
  <svg width="28" height="12" style="vertical-align:middle;margin-right:6px;">
    <line x1="0" y1="6" x2="22" y2="6" stroke="{ref_color}" stroke-width="1.5"/>
    <polygon points="22,3 28,6 22,9" fill="{ref_color}"/>
  </svg> Reference
</div>
"""


def build_network(package, theme: str = "light") -> Network:
    t = THEMES[theme]
    net = Network(height="100vh", width="100%", directed=True, bgcolor=t["bgcolor"])
    net.barnes_hut(gravity=-3000, central_gravity=0.3, spring_length=120)

    for cls in package.eClassifiers:
        if isinstance(cls, EClass):
            attributes = [
                f"  {f.name} : {f.eType.name if f.eType else '?'}"
                for f in cls.eStructuralFeatures
                if not isinstance(getattr(f, "eType", None), EClass)
            ]
            tooltip = f"<b>{cls.name}</b>"
            if attributes:
                tooltip += "<br>" + "<br>".join(attributes)
            net.add_node(
                cls.name,
                label=cls.name,
                title=tooltip,
                shape="box",
                color={"background": t["class_bg"], "border": t["class_border"]},
                font={"color": t["class_font"], "size": 14},
            )

        elif isinstance(cls, EEnum):
            literals = "<br>".join(f"  {lit.name}" for lit in cls.eLiterals)
            tooltip = f"<b>«enum» {cls.name}</b><br>{literals}"
            net.add_node(
                cls.name,
                label=f"«enum»\n{cls.name}",
                title=tooltip,
                shape="box",
                color={"background": t["enum_bg"], "border": t["enum_border"]},
                font={"color": t["enum_font"], "size": 14},
            )

    node_ids = {n["id"] for n in net.nodes}

    for cls in package.eClassifiers:
        if not isinstance(cls, EClass):
            continue

        for parent in cls.eSuperTypes:
            net.add_edge(
                cls.name, parent.name,
                label="", color=t["inherit_color"],
                dashes=True, arrows="to", width=1,
            )

        for ref in cls.eStructuralFeatures:
            if not isinstance(getattr(ref, "eType", None), EClass):
                continue
            if ref.eType.name not in node_ids:
                continue
            label = f"{ref.name}\n[{multiplicity(ref)}]"
            color = t["contain_color"] if getattr(ref, "containment", False) else t["ref_color"]
            net.add_edge(
                cls.name, ref.eType.name,
                label=label, color=color,
                arrows="to", width=1.5,
                font={"color": t["edge_font"], "size": 10},
            )

    # Inject legend into the generated HTML after saving
    net._legend_html = LEGEND_HTML.format(**t)
    return net


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ecore_file", help="Path to the .ecore file")
    parser.add_argument(
        "-o", "--output",
        default=None,
        help="Output HTML file (default: <ecore_file>.html)",
    )
    parser.add_argument(
        "--theme",
        choices=["dark", "light"],
        default="light",
        help="Color theme (default: light)",
    )
    args = parser.parse_args()

    if not os.path.exists(args.ecore_file):
        print(f"Error: '{args.ecore_file}' not found.")
        return

    output = args.output or os.path.splitext(args.ecore_file)[0] + ".html"

    package = load_package(args.ecore_file)
    net = build_network(package, theme=args.theme)
    net.save_graph(output)

    # Inject the legend before the closing </body> tag
    with open(output, "r") as f:
        html = f.read()
    with open(output, "w") as f:
        f.write(html.replace("</body>", net._legend_html + "\n</body>"))

    print(f"Diagram written to {output}")


if __name__ == "__main__":
    main()
